- hosts: sheep
  become: yes
  become_user: root
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - import_tasks: "{{ playbook_dir }}/tasks/setup_requirements.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/1.install.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/2.copy.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/3.firewall.yml"
    - import_tasks: "{{ playbook_dir }}/tasks/4.start.yml"
