---
- name: Download and extract {{ memcache_version }}
  unarchive:
    src: "{{ memcache_url }}"
    dest: "/tmp/"
    remote_src: yes
  register: memcached_install

- name: Create memcached dir
  file:
    path: "{{ memcache_dir }}"
    state: directory
    mode: '0755'

- name: Install {{ memcache_version }}
  command: "sudo sh configure --prefix={{ memcache_dir }}/"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- name: sudo make
  command: "sudo make"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- name: sudo make install
  command: "sudo make install"
  args:
    chdir: "{{ install_dir }}"
  register: config_mem

- debug: msg="{{ config_mem.stdout }}"
